name: Hello World Workflow with Secret

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Secret
        run: echo $MY_SECRET

      - name: run.sh
        run: |
          chmod +x run.sh
          ./run.sh
