name: Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Secret
        run: echo $MY_SECRET

      - name: run.sh
        run: |
          chmod +x run.sh
          ./run.sh
          
      - name: executing remote ssh commands using password   
        uses: appleboy/ssh-action@ v1.0.0  
        with:     
          host: ${{ secrets.HOST }}     
          username: ${{ secrets.USERNAME }}     
          password: ${{ secrets.PASSWORD }}     
          port: 22     
          script: echo “Hello World”
